### ISSUE TITLE
Add support for gifv

### ISSUE THREAD

**Issue by mcsheffrey** [dhg/Redditate#14]
Hey, I know you're in Iceland but this is v important.

**Comment by mcsheffrey** [comment]
Fine, I'll do it

**Comment by dhg** [comment]
It's done baby. @orderedlist did it cause he's the man. https://github.com/dhg/Redditate/pull/13 Merged and in prod.

**Comment by mcsheffrey** [comment]
Shit, srry bby I'm slippin'
